### ISSUE TITLE
Message "Captcha validation failed. Refresh the page & try again!"

### ISSUE THREAD

**Issue by LucianViana** [fernando-mc/serverless-node-text-message-app#1]
When submitting the form, it displays the message, what could it be?

**Comment by fernando-mc** [comment]
Hi Lucian! If this is in reference to a course that uses this code please comment in the system there. 

Likely this is because you need to create a recaptcha account, setup the API keys, and then make sure you're completing the recaptcha process. You can also console log things out and review the logging statements in CloudWatch when this runs for more details.

Good luck!
